### PR TITLE
 Add Lab section.

### PR DESCRIPTION
**Pull request by sejinnni**
sloved: #13 

I used naming, BEM name.
I think COFFEE LAB and 카페 W 커피 연구소 is strong or em tag.

### CODE REVIEW

**Comment by yg-0103** [comment]
image src undefined 
try again

**Comment by sejinnni** [comment]
sloved: #14 
I amend class name "inner" and add image file (png)

**Comment by yg-0103** [comment]
coding convention thinking!

**Comment by yg-0103** [comment]
good amazing !

**Comment by sejinnni** [comment]
sloved: #14 
please check LAB__text 
I try to amend this class name.

**Pull request merged**
